### ISSUE TITLE
Webhook extension in docker container

### ISSUE THREAD

**Issue by onesty-dev** [wiremock/wiremock-webhooks-extension#10]
`# clone repo`
`git clone https://github.com/rodolpheche/wiremock-docker.git`

`# prepare extension folder`
`mkdir wiremock-docker/samples/random/extensions`

`# download extension`
`wget http://central.maven.org/maven2/org/wiremock/wiremock-webhooks-extension/1.0.0/wiremock-webhooks-extension-1.0.0.jar -O wiremock-docker/samples/random/extensions/wiremock-webhooks-extension-1.0.0.jar`

`# run a container using extension`
`docker run -it --rm \
  -p 2080:8080 \
  -v $PWD/wiremock-docker/samples/random/stubs:/home/wiremock \
  -v $PWD/wiremock-docker/samples/random/extensions:/var/wiremock/extensions \
  rodolpheche/wiremock \
    --extensions org.wiremock.webhooks.Webhooks`

The Result is:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:75)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:71)
	at wiremock.com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1334)
	at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1296)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.asMap(ExtensionLoader.java:43)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.loadExtension(ExtensionLoader.java:32)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.load(ExtensionLoader.java:39)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.extensionsOfType(CommandLineOptions.java:311)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:89)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:72)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:125)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
`

My second try was to build the fatJar by myself and copy it into the extension folder. The result is:

`Exception in thread "main" java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient()Lorg/apache/http/impl/client/CloseableHttpClient;
	at org.wiremock.webhooks.Webhooks.<init>(Webhooks.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader$2.apply(ExtensionLoader.java:61)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader$2.apply(ExtensionLoader.java:57)
	at wiremock.com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1334)
	at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1296)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.asMap(ExtensionLoader.java:43)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.loadExtension(ExtensionLoader.java:32)
	at com.github.tomakehurst.wiremock.extension.ExtensionLoader.load(ExtensionLoader.java:39)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.extensionsOfType(CommandLineOptions.java:311)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:89)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:72)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:125)
`

How can I use the webhook extension in a docker container?

**Comment by ivanoronee** [comment]
+1

I am also experiencing similar problems. It would be great to know the fix

**Comment by LawrenceAsrikin** [comment]
I'm running into the same issue. I ended up creating a small app and running it in my own container. Here's an example: https://github.com/LawrenceAsrikin/scala-wiremock

**Comment by f-lopes** [comment]
I am also facing the same issue (inside a Docker container or not): https://github.com/wiremock/wiremock-webhooks-extension/issues/15#issuecomment-577176485

To avoid rebuilding a fat jar, you simply need to add `http-client` and `http-core` to your classpath:
```
java -cp wiremock-standalone-2.21.0.jar;wiremock-webhooks-extension-1.0.0.jar;httpclient-4.5.6.jar;httpcore-4.4.13.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions org.wiremock.webhooks.Webhooks
```

Using a Docker container:
```
FROM rodolpheche/wiremock:2.21.0-alpine

# Add desired extension
ADD https://repo1.maven.org/maven2/org/wiremock/wiremock-webhooks-extension/1.0.0/wiremock-webhooks-extension-1.0.0.jar /var/wiremock/extensions/
# Add dependencies
ADD https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar /var/wiremock/extensions/
ADD https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar /var/wiremock/extensions/

CMD ["--extensions", "org.wiremock.webhooks.Webhooks"]
```

You can also download the extension (with needed dependencies), share your directory into the container (`/var/wiremock/extensions/`) and modify the command:
```
docker run -it --rm \
  -p 8080:8080 \
  -v path-to-downloaded-extension:/var/wiremock/extensions \
  rodolpheche/wiremock --extensions org.wiremock.webhooks.Webhooks
```

**Comment by evgenijvorobey** [comment]
i have tried all proposed methods and ideas and always found the same issue: 
Exception in thread "main" java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient()Lorg/apache/http/impl/client/CloseableHttpClient;

Can anybody help?
@f-lopes did you succeed?

**Comment by corwestermaniddink** [comment]
For the error above: see https://github.com/wiremock/wiremock-webhooks-extension/issues/15#issuecomment-704956113 .. for some reason the order of the wm standalone jar and webhook jar is important. Don't ask why!

**Comment by jvissers** [comment]
> For the error above: see [#15 (comment)](https://github.com/wiremock/wiremock-webhooks-extension/issues/15#issuecomment-704956113) .. for some reason the order of the wm standalone jar and webhook jar is important. Don't ask why!

Actually for me the order is irrelevant, the issue of NoSuchMethodError for me comes regardless.
