### ISSUE TITLE
wiremock-webhooks-extension in standalone

### ISSUE THREAD

**Issue by asbraga-rebel** [wiremock/wiremock-webhooks-extension#15]
How to perform in wiremock-standalone?

Ex:   
java -jar wiremock.jar --extensions wiremock-webhooks-extension

**Comment by jgramling17** [comment]
+1 having the same issue

**Comment by adsith-pv** [comment]
Hi, @asbraga-rebel 

This can be achieved by cloning the repository, then create a .jar file with all the dependencies inside ([I did it by following this SO post](https://stackoverflow.com/questions/30791016/intellij-build-jar-artifact-containing-gradle-dependencies))

Once you have the jar you can set it as a extension with something like:

`java -cp "wiremock-webhooks-extension-1.0.0-all.jar;wiremock-standalone-2.25.1.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions "org.wiremock.webhooks.Webhooks"` 

I was using windows so probably you'll have to tweak the command if you're using a different OS.

Hopes this helps.

**Comment by jgramling17** [comment]
Hi, @adsith-pv
Thank you for your reply, I managed to get it working following your steps + the SO post. 

I am not a java dev and needed some hand holding, for anyone else like me here is a step by step that i used to get it working:

1. Pull down repo
2. Edit the build.gradle file

2.a. Remove this block of code: 
```
task addGitTag << {
    if (!shouldPublishLocally) {
        println "git tag ${version}".execute().text
        println "git push origin --tags".execute().text
    }
}
```
2.b. change the release task to have no longer reference addGitTag, here's how mine looks:
```
task release {
    dependsOn clean, jar, signArchives, uploadArchives
}
```
2.c. change your task wrapper to longer have a type of Wrapper, [see here why this is necessary](https://stackoverflow.com/a/54741656). Here's what mine looks like: 
```
task {
    gradleVersion = '6.0'
    distributionUrl = "https://services.gradle.org/distributions/gradle-$gradleVersion-all.zip"
}
```
2.d. change your gradel version to match your actual gradel version, (check by running `gradel -v`). I changed mine to 6.0. 
`gradleVersion = '6.0'`
2.e add in a custom fatJar task that creates the standalone jar we want for this extension. Again, i'm not a java dev, so i'm not sure if the location matters where you place it, for reference i used line 62:
```
jar {
    manifest {
        attributes("Manifest-Version": "1.0",
                "Main-Class": "org.wiremock.webhooks.Webhooks");
    }
}
task fatJar(type: Jar) {
    manifest.from jar.manifest
    classifier = 'all'
    from {
        configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}
```

3. Run `gradle fatJar` at the base directory of your wiremock-webhook-extension repo
4. The jar will be outputted in `YOUR-REPO-PATH\build\libs\wiremock-webhooks-extension-1.0.0-all.jar`
5. Copy that jar and place it next to your standalone wiremock .jar
6. Run this command at the directory where your wiremock standalone jar and your webhook extension jar are :
`java -cp "wiremock-webhooks-extension-1.0.0-all.jar;wiremock-standalone-2.25.1.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions "org.wiremock.webhooks.Webhooks"` (formatted for windows, if your jar filenames differ, change the command to match.)
7. Should work now!

**Comment by f-lopes** [comment]
I'm having this issue while running this command: 
```
java -cp wiremock-standalone-2.21.0.jar;wiremock-webhooks-extension-1.0.0.jar;httpclient-4.5.6.jar;httpcore-4.4.13.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions org.wiremock.webhooks.Webhooks
```

```
Exception in thread "main" java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient()Lorg/apache/http/impl/client/CloseableHttpClient;
        at org.wiremock.webhooks.Webhooks.<init>(Webhooks.java:46)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

`wiremock-webhooks-extensions` is compiled against Wiremock `2.21.0` and this jar is present in the classpath.

Diagnosing classpath using the `-verbose:class` command effectively shows that the `HttpClientFactory` is loaded as well as the `CloseableHttpClient` class: 
```
[Loaded com.github.tomakehurst.wiremock.http.HttpClientFactory from file:/var/wiremock/lib/wiremock-standalone-2.21.0.jar]
[Loaded org.apache.http.HttpEntity from file:/var/wiremock/extensions/httpcore-4.4.13.jar]
[Loaded org.apache.http.client.HttpClient from file:/var/wiremock/extensions/httpclient-4.5.6.jar]
```
The method `HttpClientFactory.createClient()` printed in the stacktrace exists in the `wiremock-standalone-2-21.0` jar: https://github.com/tomakehurst/wiremock/blob/64012fccc130aa7d4912997a2fad6d9cbb25c0f6/src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java#L132

Any hints?

**Comment by wiserve** [comment]
Thank you, jgramling17, for the instructions on setting up WireMock with this webhooks extension. I used it successfully. 

I had to make one change to the build.gradle file to get it to build. I took out the following lines around line 12:

plugins {
    id 'com.github.johnrengelman.shadow' version '1.2.3'
}

I was getting an error saying it couldn't be found during the build. I am new to Java/Gradle and I commented those lines out to see if it would work, and it did. The extension seems to be working fine for me. YMMV

**Comment by nhomble** [comment]
I get the same shading issue as @f-lopes when importing the jre8 standalone through spring-cloud-contract-wiremock with the webhook extensions. I'd really love to represent wiremock as a spring boot app and add these extensions. Without the spring library that brings in standalone, I was able to accomplish this a while back
```
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>2.18.0</version>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-webhooks-extension</artifactId>
            <version>0.0.1</version>
        </dependency>
```

**Comment by corwestermaniddink** [comment]
@f-lopes For some reason the order of classes are the reason you get this error:

Try:
java -cp wiremock-webhooks-extension-1.0.0.jar;wiremock-standalone-2.21.0.jar;httpclient-4.5.6.jar;httpcore-4.4.13.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions org.wiremock.webhooks.Webhooks instead

@nhomble Maby this will also help you if you change the order of the dependencies in the pom.xml.

@tomakehurst Something for you?

**Comment by immzi** [comment]
The reason java.lang.NoSuchMethodError occurs is because of shaded apache httpclient packages within the wiremock-standalone jar.
In fact the wiremock-standalone jar already contains everything that's required for it to run, including apache httpclient, but in a package-shaded manner.
When we explicitly include httpclient and httpcore into classpath, wiremock-webhooks-extension needs are satisfied, but once we attempt to reach wiremock-standalone's HttpClientFactory, a conflict occurs.

The problem in first place is because wiremock-webhooks-extension is not meant to run against wiremock-standalone; it's meant to run against com.github.tomakehurst:wiremock.

It's possible to make it happen though, if we rebuild the wiremock-webhooks-extension jar after performing the following steps:

1. In build.gradle - change the com.github.tomakehurst:wiremock compile dependency to com.github.tomakehurst:wiremock-standalone:
```
dependencies {
    compile "com.github.tomakehurst:wiremock-standalone:${versions.wiremock}"

    testCompile 'junit:junit:4.12'
    testCompile "org.hamcrest:hamcrest-all:1.3"
}
```

2. Resolve imports at Webhooks.java, WebhookDefinition.java to use wiremock-standalone's shaded packages, i.e.
org.apache.http.HttpResponse -> wiremock.org.apache.http.HttpResponse

After building the jar, the following should work:
`java -cp wiremock-standalone-2.27.1.jar;wiremock-webhooks-extension-1.0.0.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions org.wiremock.webhooks.Webhooks`
where wiremock-webhooks-extension-1.0.0.jar is a jar rebuilt on the previous step.

It's possible to do the same within docker as well.

**Comment by renato0307** [comment]
This worked for us:

```Dockerfile
FROM rodolpheche/wiremock:2.27.2

ADD https://repo1.maven.org/maven2/com/opentable/wiremock-body-transformer/1.1.3/wiremock-body-transformer-1.1.3.jar /var/wiremock/extensions/
ADD https://repo1.maven.org/maven2/org/wiremock/wiremock-webhooks-extension/1.0.0/wiremock-webhooks-extension-1.0.0.jar /var/wiremock/extensions/
ADD https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar /var/wiremock/extensions/
ADD https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar /var/wiremock/extensions/

CMD java $JAVA_OPTS -cp /var/wiremock/extensions/wiremock-webhooks-extension-1.0.0.jar:/var/wiremock/extensions/wiremock-standalone-2.27.2.jar:/var/wiremock/extensions/httpclient-4.5.6.jar:/var/wiremock/extensions/httpcore-4.4.13.jar:/var/wiremock/extensions/wiremock-body-transformer-1.1.3.jar:/var/wiremock/lib/* \
    com.github.tomakehurst.wiremock.standalone.WireMockServerRunner \
    --extensions com.opentable.extension.BodyTransformer,org.wiremock.webhooks.Webhooks
```

**Comment by evgeny-tumashchick** [comment]
Hi,

I used provided istructions to build and run wiremock with extension on windows
Thanks to all comments everything worked
But when I tried to build and run same two jars on docker I got error that main class com.github.tomakehurst.wiremock.standalone.WireMockServerRunner could not be found.

The fix is really simlpe but I decided to provide it here as this issue log seems to become some kind of documentation :)

So the original start command is 
`java -cp "wiremock-webhooks-extension.jar;wiremock-standalone.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions "org.wiremock.webhooks.Webhooks"`

and for docker u should use `:` instead `;` for classpath
the final start command would look like:
`java -cp "wiremock-webhooks-extension.jar:wiremock-standalone.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions "org.wiremock.webhooks.Webhooks"`

For me all worked well and docker was able to run wiremock wih extension

For my puprose I also updated java to 8 version in build gradle wiremock-webhooks-extension and used wiremock-jre8-standalone jdk. Pretty shure it will work for java 7 on docker

**Comment by tomakehurst** [comment]
New version coming up in the next WireMock release that will run standalone, support templating, delays and multiple webhooks per stub.

The docs are here if you'd like a quick look: https://github.com/tomakehurst/wiremock/blob/webhooks-core-extension/docs-v2/_docs/webhooks-and-callbacks.md
